### ISSUE TITLE
Task List | 任务认领处 

### ISSUE THREAD

**Issue by aJiea** [ButterflyAndHurricane/ButterflyAndHurricane#1]
4wd5

【主线】
- [x] 蝴蝶效应原理查询 | 时间开销1h

【副线】
- [x] 仓库 wiki 和 read.md 优化
- [ ] 蝴蝶和飓风代表意象，诗词、歌词化 | 时间开销：每日积累更新
- [ ] 蝴蝶和飓风主题音乐收集（个人爱好） 

5wd0

【主线】
- [ ] 提纲
- [ ] 提纲提交、讨论和通过

【副线】
- [ ] 知识管理平台竞品补充： evernote, zotero
- [x] 分享链接反馈平台竞品补充: pearltree，在行，github，linkedin
- [ ] 集合两者的【知识管理+输出+分享反馈】 蝴蝶和飓风类似项目竞品发现
- [ ] 把人或人生比作蝴蝶的古文或精美句子。微小的事物和蝴蝶之间的比喻。

**Comment by gunuo** [comment]
我先做readme优化吧。

**Comment by zjutracy** [comment]
抱歉，不知道个人信息更新在何处，是否可以放在这里？

坐标：杭州
姓名：冯敬俊
职业：HR
描述：与此次项目有关的经历，去年作为后期联合创始人运营DISC社群，并作为骨干成功帮助DISC社群荣获2016CSTD中国人才发展十大创新之一。同时，我自身对社群运营也有浓厚的兴趣

**Comment by gunuo** [comment]
你好像还没有加入这个库啊~~
